name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python:
        - '3.7'
        - '3.8'
        - '3.9'
        - '3.10'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}

    - name: Install package
      run: pip install .[test]

    - name: Run tests
      run: pytest

    - name: Store wheel as artifact
      uses: actions/upload-artifact@v2
      if: matrix.python == '3.10'
      with:
        name: wheels
        path: dist
        if-no-files-found: ignore

  docs:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - uses: actions/checkout@v2
   
    - name: Setup Python
      uses: actions/setup-python@v2

    - name: Download wheels from artifact storage
      uses: actions/download-artifact@v2
      with:
        name: wheels
        path: dist

    - name: Install from wheel
      run: |
        pip install dist/*.whl[docs]

    - name: Build docs
      run: sphinx-build -b html docs dist-docs

    - name: Store docs HTML as artifact
      uses: actions/upload-artifact@v2
      with:
        name: docs
        path: dist-docs

  publish-wheels:
    runs-on: ubuntu-latest

    needs: [build, docs]

    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')

    steps:
    - name: Download wheels from artifact storage
      uses: actions/download-artifact@v2
      with:
        name: wheels
        path: dist

    - name: Setup Python
      uses: actions/setup-python@v2
    
    - name: Upload wheels to PyPI
      run: |
        pip install twine
        twine upload -u __token__ -p ${{ secrets.PYPI_TOKEN }} --skip-existing dist/*

  publish-docs:
    runs-on: ubuntu-latest

    needs: [publish-wheels]

    permissions:
      contents: write

    steps:
    - name: Download docs HTML from artifact storage
      uses: actions/download-artifact@v2
      with:
        name: docs
        path: dist-docs

    - name: Upload docs to GitHub Pages
      uses: peaceiris/actions-gh-pages@47a6d63ea8b47b19328e258563aa1fbe224c0a23
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./dist-docs
